// scripts/generate-stylelint-rule-sets.mts
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

// 输出目录 - 已根据你的需求改为 stylelint-rule-sets
const OUT_DIR = path.resolve(__dirname, "../src/stylelint-rule-sets");

if (!fs.existsSync(OUT_DIR)) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
}

/**
 * 获取某个 npm 包的根目录
 */
function getPackageRoot(pkgName: string): string {
  const pkgJsonPath = require.resolve(`${pkgName}/package.json`);
  return path.dirname(pkgJsonPath);
}

/**
 * 尝试在包目录寻找 rules 目录
 */
function findRulesDir(pkgName: string): string | null {
  const root = getPackageRoot(pkgName);
  const candidates = ["rules", "dist/rules", "lib/rules", "src/rules"];

  for (const rel of candidates) {
    const full = path.join(root, rel);
    if (fs.existsSync(full) && fs.statSync(full).isDirectory()) {
      return full;
    }
  }
  return null;
}

/**
 * 扫描 rules 目录
 */
function scanRulesFromFs(pkgName: string, prefix = ""): string[] {
  const dir = findRulesDir(pkgName);
  if (!dir) {
    console.warn(`[warn] Cannot find rules dir for ${pkgName}`);
    return [];
  }

  const files = fs
    .readdirSync(dir)
    .filter((f) => [".js", ".cjs", ".mjs"].includes(path.extname(f)));

  return files
    .map((f) => path.basename(f, path.extname(f)))
    .map((name) => (prefix ? `${prefix}/${name}` : name))
    .sort();
}

/**
 * 扫描插件导出的 rules 对象（如@stylistic/stylelint-plugin / stylelint-order）
 */
function scanRulesFromExport(pkgName: string, prefix = ""): string[] {
  const mod = require(pkgName);
  const rulesObj =
    (mod && (mod.rules || mod.default?.rules)) ??
    {}; // 有些包 default.rules 中

  return Object.keys(rulesObj)
    .map((name) => (prefix ? `${prefix}/${name}` : name))
    .sort();
}

/**
 * 输出 TS 文件
 */
function writeRuleSetTs(fileName: string, exportName: string, rules: string[]) {
  const fullPath = path.join(OUT_DIR, fileName);
  const content =
    `// AUTO-GENERATED BY scripts/generate-stylelint-rule-sets.mts\n` +
    `// DO NOT EDIT MANUALLY.\n\n` +
    `export const ${exportName} = ${JSON.stringify(rules, null, 2)} as const;\n`;

  fs.writeFileSync(fullPath, content, "utf8");
  console.log(`[ok] Generated ${fileName} (${rules.length} rules)`);
}

/**
 * 主流程
 */
function main() {
  // 1. Stylelint core
  const coreRules = scanRulesFromFs("stylelint", "");
  writeRuleSetTs("core.ts", "coreRules", coreRules);

  // 2. @stylistic/stylelint-plugin
  const stylisticRules = scanRulesFromExport(
    "@stylistic/stylelint-plugin",
    "@stylistic"
  );
  writeRuleSetTs("stylistic.ts", "stylisticRules", stylisticRules);

  // 3. stylelint-order
  const orderRules = scanRulesFromExport("stylelint-order", "order");
  writeRuleSetTs("order.ts", "orderRules", orderRules);

  // 4. stylelint-scss
  const scssRules = scanRulesFromFs("stylelint-scss", "scss");
  writeRuleSetTs("scss.ts", "scssRules", scssRules);

  // 5. stylelint-less
  const lessRules = scanRulesFromFs("stylelint-less", "less");
  writeRuleSetTs("less.ts", "lessRules", lessRules);

  // 6. stylelint-stylus
  const stylusRules = scanRulesFromFs("stylelint-stylus", "stylus");
  writeRuleSetTs("stylus.ts", "stylusRules", stylusRules);

  console.log(`✨ All rule-sets generated successfully!`);
}

main();
