// AUTO-GENERATED BY scripts/generate-stylelint-rule-sets.js
// DO NOT EDIT MANUALLY.

export const lessRules = [
  'less/color-hex-case',
  'less/color-no-hex',
  'less/color-no-invalid-hex',
  'less/no-duplicate-variables',
];
